export const INGREDIENT_LIST = [
  { name: "apple", calories: 52, protein: 0, carbs: 14, fat: 0 },
  { name: "banana", calories: 89, protein: 1, carbs: 23, fat: 0 },
  { name: "orange", calories: 47, protein: 1, carbs: 12, fat: 0 },
  { name: "strawberry", calories: 32, protein: 1, carbs: 8, fat: 0 },
  { name: "blueberry", calories: 57, protein: 1, carbs: 14, fat: 0 },
  { name: "raspberry", calories: 52, protein: 1, carbs: 12, fat: 1 },
  { name: "blackberry", calories: 43, protein: 1, carbs: 10, fat: 0 },
  { name: "pineapple", calories: 50, protein: 1, carbs: 13, fat: 0 },
  { name: "mango", calories: 60, protein: 1, carbs: 15, fat: 0 },
  { name: "grape", calories: 69, protein: 1, carbs: 18, fat: 0 },
  { name: "watermelon", calories: 30, protein: 1, carbs: 8, fat: 0 },
  { name: "pear", calories: 57, protein: 0, carbs: 15, fat: 0 },
  { name: "peach", calories: 39, protein: 1, carbs: 10, fat: 0 },
  { name: "plum", calories: 46, protein: 1, carbs: 11, fat: 0 },
  { name: "cherry", calories: 63, protein: 1, carbs: 16, fat: 0 },

  { name: "broccoli", calories: 34, protein: 3, carbs: 7, fat: 0 },
  { name: "spinach", calories: 23, protein: 3, carbs: 4, fat: 0 },
  { name: "kale", calories: 49, protein: 4, carbs: 9, fat: 1 },
  { name: "carrot", calories: 41, protein: 1, carbs: 10, fat: 0 },
  { name: "sweet potato", calories: 86, protein: 2, carbs: 20, fat: 0 },
  { name: "potato", calories: 77, protein: 2, carbs: 17, fat: 0 },
  { name: "onion", calories: 40, protein: 1, carbs: 9, fat: 0 },
  { name: "garlic", calories: 149, protein: 6, carbs: 33, fat: 1 },
  { name: "bell pepper", calories: 31, protein: 1, carbs: 6, fat: 0 },
  { name: "cucumber", calories: 15, protein: 1, carbs: 4, fat: 0 },
  { name: "zucchini", calories: 17, protein: 1, carbs: 3, fat: 0 },
  { name: "eggplant", calories: 25, protein: 1, carbs: 6, fat: 0 },
  { name: "tomato", calories: 18, protein: 1, carbs: 4, fat: 0 },
  { name: "mushroom", calories: 22, protein: 3, carbs: 3, fat: 0 },
  { name: "lettuce", calories: 15, protein: 1, carbs: 3, fat: 0 },

  { name: "chicken breast", calories: 165, protein: 31, carbs: 0, fat: 4 },
  { name: "ground beef", calories: 250, protein: 26, carbs: 0, fat: 17 },
  { name: "pork chop", calories: 231, protein: 25, carbs: 0, fat: 14 },
  { name: "bacon", calories: 541, protein: 37, carbs: 1, fat: 42 },
  { name: "turkey", calories: 189, protein: 29, carbs: 0, fat: 7 },
  { name: "salmon", calories: 208, protein: 20, carbs: 0, fat: 13 },
  { name: "tuna", calories: 132, protein: 29, carbs: 0, fat: 1 },
  { name: "shrimp", calories: 99, protein: 24, carbs: 0, fat: 0 },
  { name: "cod", calories: 82, protein: 18, carbs: 0, fat: 1 },
  { name: "sardines", calories: 208, protein: 25, carbs: 0, fat: 11 },

  { name: "egg", calories: 155, protein: 13, carbs: 1, fat: 11 },
  { name: "milk", calories: 60, protein: 3, carbs: 5, fat: 3 },
  { name: "cheddar cheese", calories: 403, protein: 25, carbs: 1, fat: 33 },
  { name: "mozzarella", calories: 280, protein: 28, carbs: 3, fat: 17 },
  { name: "yogurt", calories: 59, protein: 10, carbs: 4, fat: 0 },
  { name: "butter", calories: 717, protein: 1, carbs: 0, fat: 81 },
  { name: "cream", calories: 340, protein: 2, carbs: 3, fat: 36 },

  { name: "white rice", calories: 130, protein: 2, carbs: 28, fat: 0 },
  { name: "brown rice", calories: 123, protein: 3, carbs: 26, fat: 1 },
  { name: "quinoa", calories: 120, protein: 4, carbs: 21, fat: 2 },
  { name: "oats", calories: 389, protein: 17, carbs: 66, fat: 7 },
  { name: "barley", calories: 354, protein: 12, carbs: 73, fat: 2 },
  { name: "corn", calories: 86, protein: 3, carbs: 19, fat: 1 },
  { name: "whole wheat bread", calories: 247, protein: 13, carbs: 41, fat: 4 },
  { name: "white bread", calories: 265, protein: 9, carbs: 49, fat: 3 },
  { name: "pasta", calories: 131, protein: 5, carbs: 25, fat: 1 },
  { name: "couscous", calories: 112, protein: 4, carbs: 23, fat: 0 },

  { name: "lentils", calories: 116, protein: 9, carbs: 20, fat: 0 },
  { name: "chickpeas", calories: 164, protein: 9, carbs: 27, fat: 3 },
  { name: "black beans", calories: 132, protein: 9, carbs: 24, fat: 1 },
  { name: "kidney beans", calories: 127, protein: 9, carbs: 23, fat: 1 },
  { name: "soybeans", calories: 173, protein: 16, carbs: 10, fat: 9 },
  { name: "tofu", calories: 76, protein: 8, carbs: 2, fat: 5 },
  { name: "tempeh", calories: 193, protein: 20, carbs: 9, fat: 11 },

  { name: "almonds", calories: 579, protein: 21, carbs: 22, fat: 50 },
  { name: "walnuts", calories: 654, protein: 15, carbs: 14, fat: 65 },
  { name: "cashews", calories: 553, protein: 18, carbs: 30, fat: 44 },
  { name: "peanuts", calories: 567, protein: 26, carbs: 16, fat: 49 },
  { name: "chia seeds", calories: 486, protein: 17, carbs: 42, fat: 31 },
  { name: "flax seeds", calories: 534, protein: 18, carbs: 29, fat: 42 },
  { name: "pumpkin seeds", calories: 559, protein: 30, carbs: 11, fat: 49 },
  { name: "sunflower seeds", calories: 584, protein: 21, carbs: 20, fat: 51 },

  { name: "olive oil", calories: 884, protein: 0, carbs: 0, fat: 100 },
  { name: "coconut oil", calories: 862, protein: 0, carbs: 0, fat: 100 },
  { name: "vegetable oil", calories: 884, protein: 0, carbs: 0, fat: 100 },
  { name: "avocado", calories: 160, protein: 2, carbs: 9, fat: 15 },

  { name: "honey", calories: 304, protein: 0, carbs: 82, fat: 0 },
  { name: "maple syrup", calories: 260, protein: 0, carbs: 67, fat: 0 },
  { name: "white sugar", calories: 387, protein: 0, carbs: 100, fat: 0 },
  { name: "brown sugar", calories: 380, protein: 0, carbs: 98, fat: 0 },

  { name: "dark chocolate", calories: 546, protein: 5, carbs: 61, fat: 31 },
  { name: "milk chocolate", calories: 535, protein: 8, carbs: 59, fat: 30 },

  { name: "mayonnaise", calories: 680, protein: 1, carbs: 1, fat: 75 },
  { name: "ketchup", calories: 112, protein: 1, carbs: 26, fat: 0 },
  { name: "mustard", calories: 66, protein: 4, carbs: 6, fat: 4 },
  { name: "soy sauce", calories: 53, protein: 8, carbs: 5, fat: 0 },

  { name: "basil", calories: 23, protein: 3, carbs: 2, fat: 1 },
  { name: "parsley", calories: 36, protein: 3, carbs: 6, fat: 1 },
  { name: "cilantro", calories: 23, protein: 2, carbs: 4, fat: 1 },
  { name: "ginger", calories: 80, protein: 2, carbs: 18, fat: 1 },
  { name: "turmeric", calories: 354, protein: 8, carbs: 65, fat: 10 },

  { name: "cabbage", calories: 25, protein: 1, carbs: 6, fat: 0 },
  { name: "cauliflower", calories: 25, protein: 2, carbs: 5, fat: 0 },
  { name: "brussels sprouts", calories: 43, protein: 3, carbs: 9, fat: 0 },
  { name: "asparagus", calories: 20, protein: 2, carbs: 4, fat: 0 },
  { name: "green beans", calories: 31, protein: 2, carbs: 7, fat: 0 },
  { name: "peas", calories: 81, protein: 5, carbs: 14, fat: 0 },
  { name: "radish", calories: 16, protein: 1, carbs: 3, fat: 0 },
  { name: "beet", calories: 43, protein: 2, carbs: 10, fat: 0 },
  { name: "turnip", calories: 28, protein: 1, carbs: 6, fat: 0 },
  { name: "leek", calories: 61, protein: 2, carbs: 14, fat: 0 },
];

export const DIETS = [
  { name: "vegetarian" },
  { name: "vegan" },
  { name: "pescatarian" },
  { name: "flexitarian" },
  { name: "keto" },
  { name: "paleo" },
  { name: "mediterranean" },
  { name: "dash" },
  { name: "whole30" },
  { name: "low carb" },
  { name: "low fat" },
  { name: "high protein" },
  { name: "plant based" },
  { name: "gluten free" },
  { name: "dairy free" },
  { name: "soy free" },
  { name: "nut free" },
  { name: "egg free" },
  { name: "shellfish free" },
  { name: "halal" },
  { name: "kosher" },
  { name: "raw food" },
  { name: "alkaline" },
  { name: "anti inflammatory" },
  { name: "gut health" },
  { name: "fodmap low" },
  { name: "diabetic friendly" },
  { name: "heart healthy" },
  { name: "weight loss" },
  { name: "bulking" },
  { name: "cutting" },
  { name: "athlete performance" },
  { name: "pregnancy nutrition" },
  { name: "lactation diet" },
  { name: "intermittent fasting" },
  { name: "ayurvedic" },
  { name: "macrobiotic" },
  { name: "carnivore" },
  { name: "south beach diet" },
  { name: "zone diet" },
];

export const ALLERGIES = [
  { name: "peanuts" },
  { name: "tree nuts" },
  { name: "milk" },
  { name: "eggs" },
  { name: "wheat" },
  { name: "soy" },
  { name: "fish" },
  { name: "shellfish" },
  { name: "sesame" },
  { name: "gluten" },
  { name: "lactose" },
  { name: "corn" },
  { name: "mustard" },
  { name: "celery" },
  { name: "sulfites" },
  { name: "mollusks" },
  { name: "lupin" },
  { name: "coconut" },
  { name: "garlic" },
  { name: "onion" },
];
